---
# tasks file for mebooks.ansible-role-docker-tomcat

- name: Debug tomcat var
  debug: var=tomcat
  tags:
  - traefik
  - tomcat
  - docker

- name: Ensure tomcat directories exist
  file:
    path: "{{ item }}"
    state: directory
  with_items:
  - /etc/tomcat
  - /etc/tomcat/webapps
  tags:
  - traefik
  - tomcat
  - docker

# https://hub.docker.com/_/tomcat/
- name: Deploy tomcat container
  docker_container:
    name: tomcat
    image: tomcat:alpine
    restart_policy: unless-stopped
    volumes:
    - /etc/tomcat/webapps:/usr/local/tomcat/webapps:rw
    - /etc/tomcat/temp:/usr/local/tomcat/temp:rw
    labels:
      traefik.enable: "true"
      traefik.backend: epubcheck
      traefik.frontend.rule: "Host:epubcheck.{{ tomcat.domain }}; AddPrefix: /epubcheck"
      traefik.port: "8080"
      com.datadoghq.ad.logs: '[{"source": "do.mebooks.co.nz", "service": "tomcat"}]'
  tags:
  - traefik
  - tomcat
  - docker
